"""Add custom fields and HubSpot integration to plugs table

Revision ID: 0b63383767c3
Revises: bfc48fb8c720
Create Date: 2025-09-23 07:12:15.308619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b63383767c3'
down_revision = 'bfc48fb8c720'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugs', sa.Column('custom_network_type', sa.String(length=64), nullable=True))
    op.add_column('plugs', sa.Column('custom_business_type', sa.String(length=64), nullable=True))
    op.add_column('plugs', sa.Column('hubspot_pipeline_stage', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugs', 'hubspot_pipeline_stage')
    op.drop_column('plugs', 'custom_business_type')
    op.drop_column('plugs', 'custom_network_type')
    # ### end Alembic commands ###
