"""Add events module with agenda, expenses, media, and event-plug associations

Revision ID: 236371dc71d1
Revises: 6cb676c6e591
Create Date: 2025-09-24 10:57:21.104743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236371dc71d1'
down_revision = '6cb676c6e591'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
