"""Create events tables with proper table names

Revision ID: 299d75f838b4
Revises: 236371dc71d1
Create Date: 2025-09-24 11:21:31.475345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299d75f838b4'
down_revision = '236371dc71d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_name', sa.String(length=128), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_date > start_date', name='check_end_after_start'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title', 'start_date', name='unique_user_event')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_deleted_at'), 'events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_events_end_date'), 'events', ['end_date'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_is_deleted'), 'events', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_index(op.f('ix_events_updated_at'), 'events', ['updated_at'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('event_agendas',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('day > 0', name='check_positive_day'),
    sa.CheckConstraint('duration_minutes > 0', name='check_positive_duration'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_agendas_created_at'), 'event_agendas', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_agendas_day'), 'event_agendas', ['day'], unique=False)
    op.create_index(op.f('ix_event_agendas_deleted_at'), 'event_agendas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_event_agendas_event_id'), 'event_agendas', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_agendas_id'), 'event_agendas', ['id'], unique=False)
    op.create_index(op.f('ix_event_agendas_is_deleted'), 'event_agendas', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_event_agendas_start_time'), 'event_agendas', ['start_time'], unique=False)
    op.create_index(op.f('ix_event_agendas_updated_at'), 'event_agendas', ['updated_at'], unique=False)
    op.create_table('event_expenses',
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name='check_non_negative_amount'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_expenses_amount'), 'event_expenses', ['amount'], unique=False)
    op.create_index(op.f('ix_event_expenses_category'), 'event_expenses', ['category'], unique=False)
    op.create_index(op.f('ix_event_expenses_created_at'), 'event_expenses', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_expenses_deleted_at'), 'event_expenses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_event_expenses_event_id'), 'event_expenses', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_expenses_id'), 'event_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_event_expenses_is_deleted'), 'event_expenses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_event_expenses_updated_at'), 'event_expenses', ['updated_at'], unique=False)
    op.create_table('event_media',
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_media_created_at'), 'event_media', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_media_deleted_at'), 'event_media', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_event_media_event_id'), 'event_media', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_media_file_type'), 'event_media', ['file_type'], unique=False)
    op.create_index(op.f('ix_event_media_id'), 'event_media', ['id'], unique=False)
    op.create_index(op.f('ix_event_media_is_deleted'), 'event_media', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_event_media_updated_at'), 'event_media', ['updated_at'], unique=False)
    op.create_table('event_plugs',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('plug_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plug_id'], ['plugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'plug_id', name='unique_event_plug')
    )
    op.create_index(op.f('ix_event_plugs_created_at'), 'event_plugs', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_plugs_deleted_at'), 'event_plugs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_event_plugs_event_id'), 'event_plugs', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_plugs_id'), 'event_plugs', ['id'], unique=False)
    op.create_index(op.f('ix_event_plugs_is_deleted'), 'event_plugs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_event_plugs_plug_id'), 'event_plugs', ['plug_id'], unique=False)
    op.create_index(op.f('ix_event_plugs_priority'), 'event_plugs', ['priority'], unique=False)
    op.create_index(op.f('ix_event_plugs_updated_at'), 'event_plugs', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_plugs_updated_at'), table_name='event_plugs')
    op.drop_index(op.f('ix_event_plugs_priority'), table_name='event_plugs')
    op.drop_index(op.f('ix_event_plugs_plug_id'), table_name='event_plugs')
    op.drop_index(op.f('ix_event_plugs_is_deleted'), table_name='event_plugs')
    op.drop_index(op.f('ix_event_plugs_id'), table_name='event_plugs')
    op.drop_index(op.f('ix_event_plugs_event_id'), table_name='event_plugs')
    op.drop_index(op.f('ix_event_plugs_deleted_at'), table_name='event_plugs')
    op.drop_index(op.f('ix_event_plugs_created_at'), table_name='event_plugs')
    op.drop_table('event_plugs')
    op.drop_index(op.f('ix_event_media_updated_at'), table_name='event_media')
    op.drop_index(op.f('ix_event_media_is_deleted'), table_name='event_media')
    op.drop_index(op.f('ix_event_media_id'), table_name='event_media')
    op.drop_index(op.f('ix_event_media_file_type'), table_name='event_media')
    op.drop_index(op.f('ix_event_media_event_id'), table_name='event_media')
    op.drop_index(op.f('ix_event_media_deleted_at'), table_name='event_media')
    op.drop_index(op.f('ix_event_media_created_at'), table_name='event_media')
    op.drop_table('event_media')
    op.drop_index(op.f('ix_event_expenses_updated_at'), table_name='event_expenses')
    op.drop_index(op.f('ix_event_expenses_is_deleted'), table_name='event_expenses')
    op.drop_index(op.f('ix_event_expenses_id'), table_name='event_expenses')
    op.drop_index(op.f('ix_event_expenses_event_id'), table_name='event_expenses')
    op.drop_index(op.f('ix_event_expenses_deleted_at'), table_name='event_expenses')
    op.drop_index(op.f('ix_event_expenses_created_at'), table_name='event_expenses')
    op.drop_index(op.f('ix_event_expenses_category'), table_name='event_expenses')
    op.drop_index(op.f('ix_event_expenses_amount'), table_name='event_expenses')
    op.drop_table('event_expenses')
    op.drop_index(op.f('ix_event_agendas_updated_at'), table_name='event_agendas')
    op.drop_index(op.f('ix_event_agendas_start_time'), table_name='event_agendas')
    op.drop_index(op.f('ix_event_agendas_is_deleted'), table_name='event_agendas')
    op.drop_index(op.f('ix_event_agendas_id'), table_name='event_agendas')
    op.drop_index(op.f('ix_event_agendas_event_id'), table_name='event_agendas')
    op.drop_index(op.f('ix_event_agendas_deleted_at'), table_name='event_agendas')
    op.drop_index(op.f('ix_event_agendas_day'), table_name='event_agendas')
    op.drop_index(op.f('ix_event_agendas_created_at'), table_name='event_agendas')
    op.drop_table('event_agendas')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_updated_at'), table_name='events')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_is_deleted'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_end_date'), table_name='events')
    op.drop_index(op.f('ix_events_deleted_at'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
