"""Replace custom fields with flexible custom_data JSON field

Revision ID: 4735226a00aa
Revises: 0b63383767c3
Create Date: 2025-09-23 07:20:55.107231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4735226a00aa'
down_revision = '0b63383767c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugs', sa.Column('custom_data', sa.JSON(), nullable=True))
    op.drop_column('plugs', 'custom_business_type')
    op.drop_column('plugs', 'custom_network_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugs', sa.Column('custom_network_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('plugs', sa.Column('custom_business_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('plugs', 'custom_data')
    # ### end Alembic commands ###
