"""Change network_type and business_type from enum to string

Revision ID: 6cb676c6e591
Revises: 4735226a00aa
Create Date: 2025-09-23 07:22:37.137906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cb676c6e591'
down_revision = '4735226a00aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugs', 'network_type',
               existing_type=postgresql.ENUM('NEW_CLIENT', 'EXISTING_CLIENT', 'NEW_PARTNERSHIP', 'EXISTING_PARTNERSHIP', 'VENDOR', 'INVESTOR', 'MENTOR', 'OTHER', name='networktype'),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('plugs', 'business_type',
               existing_type=postgresql.ENUM('BIOTECH', 'DIRECT_CARE', 'PHARMACEUTICALS', 'MEDICAL_DEVICES', 'HEALTH_TECH', 'HOSPITAL_HEALTH_SYSTEM', 'CRO', 'OTHER', name='businesstype'),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugs', 'business_type',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('BIOTECH', 'DIRECT_CARE', 'PHARMACEUTICALS', 'MEDICAL_DEVICES', 'HEALTH_TECH', 'HOSPITAL_HEALTH_SYSTEM', 'CRO', 'OTHER', name='businesstype'),
               existing_nullable=True)
    op.alter_column('plugs', 'network_type',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('NEW_CLIENT', 'EXISTING_CLIENT', 'NEW_PARTNERSHIP', 'EXISTING_PARTNERSHIP', 'VENDOR', 'INVESTOR', 'MENTOR', 'OTHER', name='networktype'),
               existing_nullable=True)
    # ### end Alembic commands ###
