"""Add coordinate fields to events table

Revision ID: 76b95c39d174
Revises: 299d75f838b4
Create Date: 2025-09-27 14:13:41.153125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76b95c39d174'
down_revision = '299d75f838b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('events', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('events', sa.Column('location_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_events_latitude'), 'events', ['latitude'], unique=False)
    op.create_index(op.f('ix_events_longitude'), 'events', ['longitude'], unique=False)
    
    # Add coordinate validation constraints
    op.create_check_constraint('check_latitude_range', 'events', 'latitude >= -90 AND latitude <= 90')
    op.create_check_constraint('check_longitude_range', 'events', 'longitude >= -180 AND longitude <= 180')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop constraints first
    op.drop_constraint('check_longitude_range', 'events', type_='check')
    op.drop_constraint('check_latitude_range', 'events', type_='check')
    
    op.drop_index(op.f('ix_events_longitude'), table_name='events')
    op.drop_index(op.f('ix_events_latitude'), table_name='events')
    op.drop_column('events', 'location_metadata')
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'latitude')
    # ### end Alembic commands ###
