"""add_batch_id_to_event_media

Revision ID: b1979620300f
Revises: ed32759b7fb0
Create Date: 2025-09-30 16:52:24.749743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1979620300f'
down_revision = 'ed32759b7fb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_media', sa.Column('batch_id', sa.UUID(), nullable=True, comment='Groups media files uploaded together as a zone/batch'))
    op.create_index(op.f('ix_event_media_batch_id'), 'event_media', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_media_batch_id'), table_name='event_media')
    op.drop_column('event_media', 'batch_id')
    # ### end Alembic commands ###
