"""make_event_and_plug_fields_nullable

Revision ID: b3b09e687ad6
Revises: 7a9d6f4f8420
Create Date: 2025-10-02 06:31:14.226606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3b09e687ad6'
down_revision = '7a9d6f4f8420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('events', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('events', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('plugs', 'first_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('plugs', 'last_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugs', 'last_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('plugs', 'first_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('events', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('events', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
