"""add_event_plug_media_table

Revision ID: ed32759b7fb0
Revises: f852d93efa1a
Create Date: 2025-09-29 11:04:20.047594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed32759b7fb0'
down_revision = 'f852d93efa1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_plug_media',
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('media_category', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('plug_id', sa.UUID(), nullable=False),
    sa.Column('event_plug_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("media_category IN ('snap', 'voice')", name='check_media_category'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_plug_id'], ['event_plugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plug_id'], ['plugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_plug_media_created_at'), 'event_plug_media', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_plug_media_deleted_at'), 'event_plug_media', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_event_plug_media_event_id'), 'event_plug_media', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_plug_media_event_plug_id'), 'event_plug_media', ['event_plug_id'], unique=False)
    op.create_index(op.f('ix_event_plug_media_id'), 'event_plug_media', ['id'], unique=False)
    op.create_index(op.f('ix_event_plug_media_is_deleted'), 'event_plug_media', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_event_plug_media_media_category'), 'event_plug_media', ['media_category'], unique=False)
    op.create_index(op.f('ix_event_plug_media_plug_id'), 'event_plug_media', ['plug_id'], unique=False)
    op.create_index(op.f('ix_event_plug_media_s3_key'), 'event_plug_media', ['s3_key'], unique=False)
    op.create_index(op.f('ix_event_plug_media_updated_at'), 'event_plug_media', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_plug_media_updated_at'), table_name='event_plug_media')
    op.drop_index(op.f('ix_event_plug_media_s3_key'), table_name='event_plug_media')
    op.drop_index(op.f('ix_event_plug_media_plug_id'), table_name='event_plug_media')
    op.drop_index(op.f('ix_event_plug_media_media_category'), table_name='event_plug_media')
    op.drop_index(op.f('ix_event_plug_media_is_deleted'), table_name='event_plug_media')
    op.drop_index(op.f('ix_event_plug_media_id'), table_name='event_plug_media')
    op.drop_index(op.f('ix_event_plug_media_event_plug_id'), table_name='event_plug_media')
    op.drop_index(op.f('ix_event_plug_media_event_id'), table_name='event_plug_media')
    op.drop_index(op.f('ix_event_plug_media_deleted_at'), table_name='event_plug_media')
    op.drop_index(op.f('ix_event_plug_media_created_at'), table_name='event_plug_media')
    op.drop_table('event_plug_media')
    # ### end Alembic commands ###
