"""add s3_key column to event_media table

Revision ID: f852d93efa1a
Revises: 76b95c39d174
Create Date: 2025-09-28 12:23:06.399382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f852d93efa1a'
down_revision = '76b95c39d174'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_media', sa.Column('s3_key', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_event_media_s3_key'), 'event_media', ['s3_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_media_s3_key'), table_name='event_media')
    op.drop_column('event_media', 's3_key')
    # ### end Alembic commands ###
